steps:
  - label: ":package: Install rocket dependencies"
    command: "install.sh"

  - label: ":construction_worker: Build the rocket"
    command: "build.sh"

  - group: "QA the rocket"
    steps:
    - label: ":rotating_light: Lint launch sequence"
      command: "lint.sh"
    - label: ":white_check_mark: Test the rocket"
      command: "test.sh"

  - label: ":rocket: Deploy the rocket"
    command: "deploy.sh"
