steps:
  - label: ":package: Install rocket dependencies"
    command: "scripts/install.sh"

  - label: ":construction_worker: Build the rocket"
    command: "scripts/build.sh"

  - group: "QA the rocket"
    steps:
    - label: ":rotating_light: Lint launch sequence"
      command: "scripts/lint.sh"
    - label: ":white_check_mark: Test the rocket"
      command: "scripts/test.sh"

  - label: ":rocket: Deploy the rocket"
    command: "scripts/deploy.sh"
