steps:
  - group: ":hammer: Build the rocket"
    steps:
      - label: ":rocket: :windows: Compile the engine"
        command: build/build.sh "WINDOWS"
      - label: ":rocket: :linux: Insert the fuel"
        command: build/build.sh "LINUX"
      - label: ":rocket: :mac: Simulate launch"
        command: build/build.sh "MAC"

  - label: ":clipboard: Test the rocket"
    command: test/test.sh

  - label: ":rocket: Deploy the rocket"
    command: deploy/deploy.sh
